# Customize page from here
root_path: ipepe.pl
title: Patryk Ptasiński's Official Website
description: Welcome to Patryk Ptasiński official website! You can check brief history of my experience, my opinions or You can contact me.

lead_name: Patryk Ptasiński
lead_subtitle: Curiosity driven Fullstack Developer
resume_download_link: "assets/resumes/Patryk_Ptasinski_Resume.pdf"

form_email: homepage@ipepe.pl
copyright_name: Patryk Ptasiński

about_me: >
  Educated and experienced software engineer with broad knowledge in the field of computer science. Working in IT for almost 10 years and interested in computers since childhood. Worked on wide range of technologies and architectures like desktop, mobile and web applications. <br/> Published multiple opensource projects and libraries. Hacktoberfest Participant and unofficial ambassador. Indie games developer. Cars and motorcycles enthusiast. Driving licence since the age of 16 with the result of 200’000+ kilometres driven to date. Rebuilt several two-stroke engines for sport/racing use. Currently exploring 3D Printing combined with microcontrollers and single board computers in areas like IoT, robotics and automation.

experiences:
  - employer_name: Skriware
    title: WebGL, React and Ruby Developer/Azure Cloud Architect
    description: 'Responsible for creating advanced Three.js based online CAD editor. Also did monitoring and full stack development for Rails application related to 3D Printing and IOT Devices. Managed and scaled Azure infrastructure spanning 8 VM and 30+ containers'
    stack: 'Three.js, React, React Ruby on Rails, NodeJS, ActionCable, PostgreSQL and Redis'
    related: 'Azure, Capistrano, MicroServices, Integration, AirBrake (Errbit), Monitoring and GitLab.'
    dates: 2018 - Present
  - employer_name: DaftCode.pl
    title: Lead Ruby Developer
    description: "Responsible for planning, estimating and distributing work in a team, architecture and quality of code for medium Rails application"
    stack: "Bootstrap, Three.js, Ruby on Rails, PostgreSQL, Redis and Elasticsearch"
    related: "Kanbanery, Capistrano, Integration, AirBrake (Errbit), Monitoring and GitLab"
    dates: 2017
  - employer_name: In4mates.com
    title: Lead Ruby Developer
    description: "Lead developer in a big project related to the accounting and business processes. Managed team of 5 developers. Responsible for architecture, maintenance, deployment - whole system development life cycle"
    stack: "Bootstrap, EmberJS, Bower, NPM, Ruby on Rails, PostgreSQL and Docker"
    related: "Jenkins, Redmine, Capistrano, Vagrant, Integration, Monitoring and GitLab."
    dates: 2015 - 2017
  - employer_name: Gaz-System.pl
    title: Systems Administrator and T2 Helpdesk
    description: "Performed second level on-site Helpdesk. Administrator of packages, applications and compliance for SCCM (2500 workstations) and on-site Aactive Directory managment (600 users and computers)."
    related: "DevOps, Zabbix, PowerShell, VBScript, Acronis, Hardware Inventory, SLA, Microsoft Deployment Toolkit."
    dates: 2012 - 2014
  - employer_name: DigitalVirgo.pl
    title: 24x7 Helpline Support
    description: "Responsible for supporting Paid SMS Gateway and part-time Helpdesk Support."
    related: "DevOps, SLA, Linux, Nagios, Scripting, Hardware Inventory and Software Lincesing."
    dates: 2012
  - employer_name: Synergia-Polska.pl
    title: Outsourced Systems Administrator and Helpdesk
    description: "Responsible for the infrastructure of multiple client companies. Developed multiple small tools and applications in Java and C-Sharp."
    related: "SLA, Monitoring, VNC, DevOps, Hardware and Software Technical Support."
    dates: 2011
  - employer_name: Lacan.com.pl
    title: Junior OpenERP Developer and Helpdesk Support
    description: "Created multiple OpenERP modules. Performed duties as Secondary Systems Administrator and resolved Helpdesk tickets."
    related: "SLA, DevOps, Spiceworks, Monitoring, VNC, Python and MySQL."
    dates: 2010

educations:
  - school_name: Polish-Japanese Academy Of Information Technology
    dates: 2012 - 2017
    url: http://www.pja.edu.pl/en/
    img_url: assets/images/education/pjatk.png
    title: Engineer degree in The Faculty of Information Technology
    speciality: Networks of Mobile Devices
    thesis: Urban navigation based on WIFI location data
    advisor: dr. inż. Michał Tomaszewski
    related: Ruby On Rails, Big data, WIFI, Android, Geolocation, PostGIS
  - school_name: Academic High School under supervision of Polish-Japanese Academy Of Information Technology
    dates: 2008 - 2011
    img_url: assets/images/education/alo.png
    url: http://liceum.pja.edu.pl/
    title: Secondary Education
    speciality: Information Technology
    related: Java, SQL, UML

projects:
  - name: Skribots Creator by Skriware
    url: https://skriware.com/robots/creator
    img_url: assets/images/projects/creator.jpg
    description: Creator is an online tool where, thanks to original Skriware blocks system, you can design any robot or construction and print it on a Skriware 3D printer.
  - name: Skrimarket by Skriware
    url: https://skrimarket.com/
    img_url: assets/images/projects/skrimarket.jpg
    description: Print and share amazing 3D designs. A dedicated market with high quality models for Skriware 3D printer.
  - name: TaxOrder
    url: https://web.archive.org/web/20180810121414/http://taxorder.pl/
    img_url: assets/images/projects/taxorder.jpg
    description: Tax Order is modern approach to managing big accounting offices. It offers a powerful system for designing any waterfall-style business processes. It also features client facing portal where You can generate or upload invoices, manage employee contracts and consult any law or accounting problems.

skills:
  - Ruby on Rails
  - JavaScript(Browser and NodeJS)
  - PostgreSQL
  - Web Crawling

  - Network File Sharing and Backup
  - Local Network Configuration for Windows and Linux
  - GameDev
  - Git
  - Linux - Ubuntu/Debian Family
  - Reverse Engineering
  - 3D Modelling
  - FDM 3D Printing
  - Android Development
  - iOS Development
  - Arduino/C++
  - AI and Data Science
  - Electronics
  - PCB making
  - Raspberry PI Development


social_buttons:
  - iconkey: github
    url: https://github.com/ipepe

#    Jekyll Config & Plugins     #
markdown: kramdown
permalink: pretty
gems:
 - jekyll-coffeescript
sass:
  style: compressed
